### ISSUE TITLE
Feature request: Cross platform support

### ISSUE THREAD

**Issue by mewmew** [katahiromz/CodeReverse#2]
The current code base seems heavily dependent on Windows. Which parts of the system are fundamentally tied to Windows (e.g. GUI) and which could be ported to other platforms? It would be great if the decompilation engine/libraries/tools would be implemented using platform independent C (i.e. POSIX). The Windows front-end GUI could make use of the engine/libraries/tools to perform the decompilation. This would enable a Linux front-end to be implemented using shared logic of the decompiler core.

**Comment by katahiromz** [comment]
I have no knowledges about other platforms.

**Comment by mewmew** [comment]
> I have no knowledge about other platforms.

No worries, CodeReverse may stay a dedicated Windows decompiler. I'll close this issue for now. It may be re-opened in the future, should cross platform support be on the radar of the project.

Happy coding.
